### ISSUE TITLE
DPOP not providing same cost solution for same input file

### ISSUE THREAD

**Issue by Evesor** [Orange-OpenSource/pyDcop#16]
I seem to be getting different _cost_ values for the attached problem whilst using the DPOP solver. This issue was present with an older version of PyDCOP, not 100% which one, and the current master branch. Whilst it makes sense for DCOP to produce different solutions with the same cost value it does not make sense that it returns different solutions with different cost values (as it is a complete algorithm). Typically I get cost between 25 and 45 however I know from using another solver that the minimum for this problem instance should be lower.

Am I missing something here?

Thanks,

[foo.txt](https://github.com/Orange-OpenSource/pyDcop/files/4099919/foo.txt)

**Comment by PierreRustOrange** [comment]
You're completely right, there something strange (and wrong!) going on here, DPOP should always return a assignment that has the same -optimal- cost.
I'll look into it , thanks for reporting the issue.

**Comment by PierreRustOrange** [comment]
Ok, that was actually simple enough.
Many of the variable in your problem are not used in any constraint, but have a cost function.
For these variable, DPOP was selecting a variable at random, ignoring the cost function.
For this reason, the variation in cost was due to these random value selection...

I have pushed a fix in the PR #17 , please let me know if it works for you and I'll merge it into master.

With the fix, dpop always returns a cost of 10 for your example dcop.

**Comment by Evesor** [comment]
Thanks Pierre, 

Seems to be running fine now. And yes I get the result of 10 also.

**Comment by PierreRustOrange** [comment]
OK great, I'll merge the PR right now.
I have opened another issue to review other algorithms;  MGM has the same bug, other algorithms might be affected too.

If you have any other problem, please file an issue :)
